# Generated by Django 3.1 on 2020-08-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('state', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rate', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.issuerate')),
                ('main_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.programminglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.owner')),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IssueRateRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='issues.issue')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.issuerate')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('repository', 'number')},
        ),
    ]
