# Generated by Django 3.1 on 2020-08-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_issuerate'),
        ('issues', '0002_issue_main_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='current_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='issue',
            name='rates',
            field=models.ManyToManyField(to='triage.IssueRate'),
        ),
    ]
