# Generated by Django 3.1 on 2020-08-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_issuerate'),
        ('issues', '0003_auto_20200823_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='rates',
        ),
        migrations.CreateModel(
            name='IssueRateRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.issuerate')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='issues.issue')),
            ],
        ),
    ]
