# Generated by Django 3.1 on 2020-08-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_issuerate'),
        ('issues', '0006_auto_20200823_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='current_rate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='triage.issuerate'),
        ),
    ]
