# Generated by Django 3.1 on 2020-08-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_issuerate'),
        ('issues', '0007_auto_20200823_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='main_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.programminglanguage'),
        ),
    ]
